//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMVCPlatform.Models.UserRights
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminUser
    {
        public System.Guid AdminUserID { get; set; }
        public string UserName { get; set; }
        public string UserPwd { get; set; }
        public Nullable<System.Guid> RoleID { get; set; }
        public string Email { get; set; }
        public string RealName { get; set; }
        public Nullable<System.Guid> BelongOrga { get; set; }
        public Nullable<int> Sex { get; set; }
        public string QQ { get; set; }
        public Nullable<System.DateTime> LoginTime { get; set; }
        public Nullable<System.DateTime> RegTime { get; set; }
        public string LoginIp { get; set; }
        public Nullable<bool> IsEnable { get; set; }
        public string Remark { get; set; }
    
        public virtual Roles Roles { get; set; }
    }
}
