//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMVCPlatform.Models.UserRights
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rights
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rights()
        {
            this.Roles_Rights = new HashSet<Roles_Rights>();
            this.UIControl_Rights = new HashSet<UIControl_Rights>();
        }
    
        public System.Guid RightsID { get; set; }
        public string RightsName { get; set; }
        public string RightsAliasName { get; set; }
        public Nullable<bool> IsEnable { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Roles_Rights> Roles_Rights { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UIControl_Rights> UIControl_Rights { get; set; }
    }
}
