//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMVCPlatform.Models.UserRights
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles_Rights
    {
        public System.Guid Roles_RightsID { get; set; }
        public Nullable<System.Guid> RoleID { get; set; }
        public Nullable<System.Guid> RightsID { get; set; }
    
        public virtual Rights Rights { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
