//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMVCPlatform.Models.UserRights
{
    using System;
    using System.Collections.Generic;
    
    public partial class UIControl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UIControl()
        {
            this.UIControl_Rights = new HashSet<UIControl_Rights>();
        }
    
        public System.Guid UIControlID { get; set; }
        public string WebSite { get; set; }
        public string Assembly { get; set; }
        public string UIControlName { get; set; }
        public string ViewName { get; set; }
        public string Path { get; set; }
        public string IndexCode { get; set; }
        public Nullable<bool> IsMenu { get; set; }
        public Nullable<System.DateTime> CreateDatetime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UIControl_Rights> UIControl_Rights { get; set; }
    }
}
