//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMVCPlatform.DAL.UserRights
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using EFMVCPlatform.Models.UserRights;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class UserRightsEntities : DbContext
    {
        public UserRightsEntities()
            : base("name=UserRightsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminUser> AdminUser { get; set; }
        public virtual DbSet<Rights> Rights { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Roles_Rights> Roles_Rights { get; set; }
        public virtual DbSet<UIControl> UIControl { get; set; }
        public virtual DbSet<UIControl_Rights> UIControl_Rights { get; set; }
    
        public virtual ObjectResult<TestProc_Result> TestProc(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TestProc_Result>("TestProc", idParameter);
        }
    }
}
